/*
E621

OpenAPI definition for E621's API. You can find the source [here](https://github.com/DonovanDMC/E621OpenAPI)<br> This document is intended to compliment E621's existing [API Documentation](https://e621.net/help/api).<br> Note if E621's api is under attack and/or cloudflare protections are enabled, the \"Try it out\" buttons here will not work.<br> If they are not working, you can check this [Unofficial Status Page](https://status.e621.ws).

API version: d69c34e
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

// AvoidPostingVersionsAPIService AvoidPostingVersionsAPI service
type AvoidPostingVersionsAPIService service

type AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest struct {
	ctx                       context.Context
	ApiService                *AvoidPostingVersionsAPIService
	limit                     *int32
	page                      *int32
	searchId                  *int32
	searchIpAddr              *string
	searchOrder               *string
	searchUpdaterName         *string
	searchUpdaterId           *string
	searchAnyNameMatches      *string
	searchArtistName          *string
	searchArtistId            *string
	searchAnyOtherNameMatches *string
	searchGroupName           *string
	searchIsActive            *bool
}

// The maximum number of results to return. Between 0 and 320.
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) Limit(limit int32) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.limit = &limit
	return r
}

// The page number of results to get. Between 1 and 750.
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) Page(page int32) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.page = &page
	return r
}

// Search for a specific id.
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) SearchId(searchId int32) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.searchId = &searchId
	return r
}

// Must be Admin+ to use. See [postgres&#39; documentation](https://www.postgresql.org/docs/9.3/functions-net.html) for information on how this is parsed. Specifically, \&quot;is contained within or equals\&quot; (&#x60;&lt;&lt;&#x3D;&#x60;).
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) SearchIpAddr(searchIpAddr string) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.searchIpAddr = &searchIpAddr
	return r
}

// The order of the results.
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) SearchOrder(searchOrder string) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.searchOrder = &searchOrder
	return r
}

// The name of the updater of the avoid posting entry.
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) SearchUpdaterName(searchUpdaterName string) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.searchUpdaterName = &searchUpdaterName
	return r
}

// The ID of the updater of the avoid posting entry.
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) SearchUpdaterId(searchUpdaterId string) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.searchUpdaterId = &searchUpdaterId
	return r
}

// Any name matching.
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) SearchAnyNameMatches(searchAnyNameMatches string) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.searchAnyNameMatches = &searchAnyNameMatches
	return r
}

// The artist name of the avoid posting entry.
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) SearchArtistName(searchArtistName string) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.searchArtistName = &searchArtistName
	return r
}

// The artist id for the avoid posting entry.
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) SearchArtistId(searchArtistId string) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.searchArtistId = &searchArtistId
	return r
}

// Any other name matching.
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) SearchAnyOtherNameMatches(searchAnyOtherNameMatches string) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.searchAnyOtherNameMatches = &searchAnyOtherNameMatches
	return r
}

// Any other name matching.
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) SearchGroupName(searchGroupName string) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.searchGroupName = &searchGroupName
	return r
}

// If the avoid posting entry is active.
func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) SearchIsActive(searchIsActive bool) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	r.searchIsActive = &searchIsActive
	return r
}

func (r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) Execute() (*SearchAvoidPostingVersions200Response, *http.Response, error) {
	return r.ApiService.SearchAvoidPostingVersionsExecute(r)
}

/*
SearchAvoidPostingVersions Search Avoid Posting Versions

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest
*/
func (a *AvoidPostingVersionsAPIService) SearchAvoidPostingVersions(ctx context.Context) AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest {
	return AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return SearchAvoidPostingVersions200Response
func (a *AvoidPostingVersionsAPIService) SearchAvoidPostingVersionsExecute(r AvoidPostingVersionsAPISearchAvoidPostingVersionsRequest) (*SearchAvoidPostingVersions200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *SearchAvoidPostingVersions200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AvoidPostingVersionsAPIService.SearchAvoidPostingVersions")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/avoid_posting_versions.json"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "")
	}
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "")
	}
	if r.searchId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search[id]", r.searchId, "")
	}
	if r.searchIpAddr != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search[ip_addr]", r.searchIpAddr, "")
	}
	if r.searchOrder != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search[order]", r.searchOrder, "")
	}
	if r.searchUpdaterName != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search[updater_name]", r.searchUpdaterName, "")
	}
	if r.searchUpdaterId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search[updater_id]", r.searchUpdaterId, "")
	}
	if r.searchAnyNameMatches != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search[any_name_matches]", r.searchAnyNameMatches, "")
	}
	if r.searchArtistName != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search[artist_name]", r.searchArtistName, "")
	}
	if r.searchArtistId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search[artist_id]", r.searchArtistId, "")
	}
	if r.searchAnyOtherNameMatches != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search[any_other_name_matches]", r.searchAnyOtherNameMatches, "")
	}
	if r.searchGroupName != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search[group_name]", r.searchGroupName, "")
	}
	if r.searchIsActive != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search[is_active]", r.searchIsActive, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
