/*
E621

OpenAPI definition for E621's API. You can find the source [here](https://github.com/DonovanDMC/E621OpenAPI)<br> This document is intended to compliment E621's existing [API Documentation](https://e621.net/help/api).<br> Note if E621's api is under attack and/or cloudflare protections are enabled, the \"Try it out\" buttons here will not work.<br> If they are not working, you can check this [Unofficial Status Page](https://status.e621.ws). 

API version: d69c34e
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi-e621-go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCommentVote200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCommentVote200Response{}

// CreateCommentVote200Response struct for CreateCommentVote200Response
type CreateCommentVote200Response struct {
	Score float32 `json:"score"`
	OurScore float32 `json:"our_score"`
}

type _CreateCommentVote200Response CreateCommentVote200Response

// NewCreateCommentVote200Response instantiates a new CreateCommentVote200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCommentVote200Response(score float32, ourScore float32) *CreateCommentVote200Response {
	this := CreateCommentVote200Response{}
	this.Score = score
	this.OurScore = ourScore
	return &this
}

// NewCreateCommentVote200ResponseWithDefaults instantiates a new CreateCommentVote200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCommentVote200ResponseWithDefaults() *CreateCommentVote200Response {
	this := CreateCommentVote200Response{}
	return &this
}

// GetScore returns the Score field value
func (o *CreateCommentVote200Response) GetScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Score
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
func (o *CreateCommentVote200Response) GetScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Score, true
}

// SetScore sets field value
func (o *CreateCommentVote200Response) SetScore(v float32) {
	o.Score = v
}

// GetOurScore returns the OurScore field value
func (o *CreateCommentVote200Response) GetOurScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.OurScore
}

// GetOurScoreOk returns a tuple with the OurScore field value
// and a boolean to check if the value has been set.
func (o *CreateCommentVote200Response) GetOurScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OurScore, true
}

// SetOurScore sets field value
func (o *CreateCommentVote200Response) SetOurScore(v float32) {
	o.OurScore = v
}

func (o CreateCommentVote200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCommentVote200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["score"] = o.Score
	toSerialize["our_score"] = o.OurScore
	return toSerialize, nil
}

func (o *CreateCommentVote200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"score",
		"our_score",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCommentVote200Response := _CreateCommentVote200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCommentVote200Response)

	if err != nil {
		return err
	}

	*o = CreateCommentVote200Response(varCreateCommentVote200Response)

	return err
}

type NullableCreateCommentVote200Response struct {
	value *CreateCommentVote200Response
	isSet bool
}

func (v NullableCreateCommentVote200Response) Get() *CreateCommentVote200Response {
	return v.value
}

func (v *NullableCreateCommentVote200Response) Set(val *CreateCommentVote200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCommentVote200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCommentVote200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCommentVote200Response(val *CreateCommentVote200Response) *NullableCreateCommentVote200Response {
	return &NullableCreateCommentVote200Response{value: val, isSet: true}
}

func (v NullableCreateCommentVote200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCommentVote200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


