/*
E621

OpenAPI definition for E621's API. You can find the source [here](https://github.com/DonovanDMC/E621OpenAPI)<br> This document is intended to compliment E621's existing [API Documentation](https://e621.net/help/api).<br> Note if E621's api is under attack and/or cloudflare protections are enabled, the \"Try it out\" buttons here will not work.<br> If they are not working, you can check this [Unofficial Status Page](https://status.e621.ws).

API version: d69c34e
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SearchPoolVersions200Response struct for SearchPoolVersions200Response
type SearchPoolVersions200Response struct {
	SearchPoolVersions200ResponseAnyOf *SearchPoolVersions200ResponseAnyOf
	ArrayOfPoolVersion                 *[]PoolVersion
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *SearchPoolVersions200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into SearchPoolVersions200ResponseAnyOf
	err = json.Unmarshal(data, &dst.SearchPoolVersions200ResponseAnyOf)
	if err == nil {
		jsonSearchPoolVersions200ResponseAnyOf, _ := json.Marshal(dst.SearchPoolVersions200ResponseAnyOf)
		if string(jsonSearchPoolVersions200ResponseAnyOf) == "{}" { // empty struct
			dst.SearchPoolVersions200ResponseAnyOf = nil
		} else {
			return nil // data stored in dst.SearchPoolVersions200ResponseAnyOf, return on the first match
		}
	} else {
		dst.SearchPoolVersions200ResponseAnyOf = nil
	}

	// try to unmarshal JSON data into ArrayOfPoolVersion
	err = json.Unmarshal(data, &dst.ArrayOfPoolVersion)
	if err == nil {
		jsonArrayOfPoolVersion, _ := json.Marshal(dst.ArrayOfPoolVersion)
		if string(jsonArrayOfPoolVersion) == "{}" { // empty struct
			dst.ArrayOfPoolVersion = nil
		} else {
			return nil // data stored in dst.ArrayOfPoolVersion, return on the first match
		}
	} else {
		dst.ArrayOfPoolVersion = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(SearchPoolVersions200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *SearchPoolVersions200Response) MarshalJSON() ([]byte, error) {
	if src.SearchPoolVersions200ResponseAnyOf != nil {
		return json.Marshal(&src.SearchPoolVersions200ResponseAnyOf)
	}

	if src.ArrayOfPoolVersion != nil {
		return json.Marshal(&src.ArrayOfPoolVersion)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableSearchPoolVersions200Response struct {
	value *SearchPoolVersions200Response
	isSet bool
}

func (v NullableSearchPoolVersions200Response) Get() *SearchPoolVersions200Response {
	return v.value
}

func (v *NullableSearchPoolVersions200Response) Set(val *SearchPoolVersions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchPoolVersions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchPoolVersions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchPoolVersions200Response(val *SearchPoolVersions200Response) *NullableSearchPoolVersions200Response {
	return &NullableSearchPoolVersions200Response{value: val, isSet: true}
}

func (v NullableSearchPoolVersions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchPoolVersions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
