/*
E621

OpenAPI definition for E621's API. You can find the source [here](https://github.com/DonovanDMC/E621OpenAPI)<br> This document is intended to compliment E621's existing [API Documentation](https://e621.net/help/api).<br> Note if E621's api is under attack and/or cloudflare protections are enabled, the \"Try it out\" buttons here will not work.<br> If they are not working, you can check this [Unofficial Status Page](https://status.e621.ws). 

API version: d69c34e
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi-e621-go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchTagVersions200ResponseAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchTagVersions200ResponseAnyOf{}

// SearchTagVersions200ResponseAnyOf No Results
type SearchTagVersions200ResponseAnyOf struct {
	TagTypeVersions []string `json:"tag_type_versions"`
}

type _SearchTagVersions200ResponseAnyOf SearchTagVersions200ResponseAnyOf

// NewSearchTagVersions200ResponseAnyOf instantiates a new SearchTagVersions200ResponseAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchTagVersions200ResponseAnyOf(tagTypeVersions []string) *SearchTagVersions200ResponseAnyOf {
	this := SearchTagVersions200ResponseAnyOf{}
	this.TagTypeVersions = tagTypeVersions
	return &this
}

// NewSearchTagVersions200ResponseAnyOfWithDefaults instantiates a new SearchTagVersions200ResponseAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchTagVersions200ResponseAnyOfWithDefaults() *SearchTagVersions200ResponseAnyOf {
	this := SearchTagVersions200ResponseAnyOf{}
	return &this
}

// GetTagTypeVersions returns the TagTypeVersions field value
func (o *SearchTagVersions200ResponseAnyOf) GetTagTypeVersions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TagTypeVersions
}

// GetTagTypeVersionsOk returns a tuple with the TagTypeVersions field value
// and a boolean to check if the value has been set.
func (o *SearchTagVersions200ResponseAnyOf) GetTagTypeVersionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TagTypeVersions, true
}

// SetTagTypeVersions sets field value
func (o *SearchTagVersions200ResponseAnyOf) SetTagTypeVersions(v []string) {
	o.TagTypeVersions = v
}

func (o SearchTagVersions200ResponseAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchTagVersions200ResponseAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tag_type_versions"] = o.TagTypeVersions
	return toSerialize, nil
}

func (o *SearchTagVersions200ResponseAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tag_type_versions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchTagVersions200ResponseAnyOf := _SearchTagVersions200ResponseAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchTagVersions200ResponseAnyOf)

	if err != nil {
		return err
	}

	*o = SearchTagVersions200ResponseAnyOf(varSearchTagVersions200ResponseAnyOf)

	return err
}

type NullableSearchTagVersions200ResponseAnyOf struct {
	value *SearchTagVersions200ResponseAnyOf
	isSet bool
}

func (v NullableSearchTagVersions200ResponseAnyOf) Get() *SearchTagVersions200ResponseAnyOf {
	return v.value
}

func (v *NullableSearchTagVersions200ResponseAnyOf) Set(val *SearchTagVersions200ResponseAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchTagVersions200ResponseAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchTagVersions200ResponseAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchTagVersions200ResponseAnyOf(val *SearchTagVersions200ResponseAnyOf) *NullableSearchTagVersions200ResponseAnyOf {
	return &NullableSearchTagVersions200ResponseAnyOf{value: val, isSet: true}
}

func (v NullableSearchTagVersions200ResponseAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchTagVersions200ResponseAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


